apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-server-app
  namespace: ta-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: result-server-app
  template:
    metadata:
      labels:
        app: result-server-app
    spec:
      containers:
      - name: result-server-app
        image: manuel123456/result-server-app:latest
        ports:
        - containerPort: 80
        startupProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3  
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
        env:
        - name: MYSQL_DATABASE_HOST
          value: "mysql"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "kubernetes"
        - name: MYSQL_DATABASE
          value: "ta-database"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"