apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql
  namespace: ta-apps
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn  
  resources:
    requests:
      storage: 2Gi